- name: download
  get_url: >
    url={{ elasticsearch.deb }}
    sha256sum={{ elasticsearch.deb_sha256 }}
    dest=/tmp/elasticsearch.deb-{{ elasticsearch.deb_sha256 }}
  register: elasticsearch_new_version

- name: install
  sudo: true
  command: >
    /usr/bin/dpkg -i /tmp/elasticsearch.deb-{{ elasticsearch.deb_sha256 }}
  when: elasticsearch_new_version | changed

- name: generate config
  sudo: true
  template: >
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    mode=0644
  notify: restart elasticsearch
  when: "'config' in elasticsearch"

- name: install plugins
  sudo: true
  command: >
    /usr/share/elasticsearch/bin/plugin -install {{ item.name }}
    creates=/usr/share/elasticsearch/plugins/{{ item.creates }}
  with_items: elasticsearch.plugins
